spring:
  application:
    name: chaekmate-auth

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  config:
    import: "optional:configserver:"    # configserver import 활성화

  cloud:
    config:
      enabled: false # Config server 사용 설정 기본 비활성화
server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://chaekmate:1234@localhost:8761/eureka
    healthcheck:
      enabled: true

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
info:
  instanceId: ${spring.application.name}:${server.port}

jwt:
  secret: ${JWT_SECRET_KEY}
  access:
    exp: ${ACCESS_TOKEN_EXPIRED_AT:3600}
  refresh:
    exp: ${REFRESH_TOKEN_EXPIRED_AT:259200}

# PAYCO OAuth 설정
payco:
  oauth:
    client-id: ${PAYCO_CLIENT_ID}
    client-secret: ${PAYCO_CLIENT_SECRET}
    redirect-uri: ${PAYCO_REDIRECT_URI}

# Dooray Webhook 설정
dooray:
  webhook:
    url: ${DOORAY_WEBHOOK_URL}

# RabbitMQ 설정
rabbitmq:
  exchange:
    name: cart.exchange
  queues:
    login-queue-name: cart.login.queue
    logout-queue-name: cart.logout.queue
    login-routing-key: cart.login
    logout-routing-key: cart.logout
# Swagger 설정
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true