# Auth Server Port
server:
  port: 9000

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_RANGE}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    # HikariCP 설정 (커넥션 풀)
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-test-query: SELECT 1
      validation-timeout: 5000

  jpa:
    hibernate:
      # create , update 금지
      ddl-auto: validate # validate 로 수정 (전체 entity  수정 후)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

# Eureka Server URL
eureka:
  client:
    service-url:
      defaultZone: http://chaekmate:1234@localhost:8761/eureka