spring:
  application:
    name: chaekmate-auth

server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://chaekmate:1234@localhost:8761/eureka

#테스트용
#eureka:
#  client:
#    enabled: false

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
jwt:
  secret: ${JWT_SECRET_KEY}
  access:
    exp: ${ACCESS_TOKEN_EXPIRED_AT:3600}
  refresh:
    exp: ${REFRESH_TOKEN_EXPIRED_AT:259200}
chaekmate:
  core:
    url: http://localhost:9100