spring:
  # Config 적용, 겹치는 설정 있으면 Config server에 의해 덮어씌워짐
  config:
    import: "optional:configserver:"    # configserver import 활성화

  cloud:
    config:
      enabled: true
      profile: prod # config-repo의 prod 프로필 사용
      label: main   # config-repo 의 main 브랜치 사용
      discovery:
        enabled: true                   # Eureka를 통해 Config Server 찾기
        service-id: chaekmate-config    # Eureka 서비스 이름
      fail-fast: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL_PROD}
    healthcheck:
      enabled: true

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
