spring:
  application:
    name: chaekmate-auth
  profiles:
    active: dev
server:
  port: 9000
jwt:
  secret: ${JWT_SECRET_KEY}
  access:
    exp: ${ACCESS_TOKEN_EXPIRED_AT:3600} # ?? ?????
  refresh:
    exp: ${REFRESH_TOKEN_EXPIRED_AT:604800} # ?? 7??